### ISSUE TITLE
Tasks: Add more endpoints

### ISSUE THREAD

**Issue by ryanwinchester** [ryanwinchester/hubspot-php#11]
**API endpoints:**

 * Endpoints
     - [x] Blog (COS)
     - [x] Blog Authors (COS)
     - [x] Blog Posts (COS)
     - [x] Blog Topics (COS)
     - [x] Contacts
     - [x] Contact Lists
     - [x] Contact Properties
     - [x] Email
     - [x] Email Events
     - [x] Engagements
     - [x] Events
     - [x] Files (COS)
     - [x] Forms
     - [x] Keywords
     - [x] Page Publishing (COS)
     - [x] Social Media
     - [x] Workflows
     - [x] Companies
     - [x] Companies Properties
     - [x] Deals
     - [ ] Templates (COS)

**Comment by RyanWinchester** [comment]
Checked off `Events`, thanks @amyboyd #15

**Comment by ryanwinchester** [comment]
thanks @lordthorzonus #27

**Comment by rubenwebs** [comment]
Hi,

Can you add the complete COS Templates API too?
http://developers.hubspot.com/docs/methods/templates/get_templates

Thanks in advance.

**Comment by ryanwinchester** [comment]
Thanks @lordthorzonus again #30

**Comment by ryanwinchester** [comment]
@rubenwebs it's been added to the list

**Comment by stratease** [comment]
@ryanwinchester going to work on the [Transactional Email API](http://developers.hubspot.com/docs/methods/email/transactional_email/single-send-overview), since that's all I need at this point. Is that something you're interested in adding?

**Comment by ryanwinchester** [comment]
@stratease I hadn't planned on working on it yet, but I'm open to any PRs to add it.

Not sure if it would be better to append it to https://github.com/ryanwinchester/hubspot-php/blob/master/src/Api/Email.php or not, though

**Comment by stratease** [comment]
It *feels* like it belongs there, but if we have been mimicking their API I'd recommend we continue that route? i.e. ```SingleEmail``` class.
![image](https://cloud.githubusercontent.com/assets/2826045/12592527/a724d92e-c421-11e5-8637-77725c12ca74.png)

**Comment by stratease** [comment]
@ryanwinchester now that I look closer, I think ```TransactionalEmail``` might make the most sense here. Thoughts?

**Comment by ryanwinchester** [comment]
Sure, makes sense. It looks like that is a paid add-on, too.

**Comment by kevin830222** [comment]
#37

**Comment by ryanwinchester** [comment]
Thanks @kevin830222 #37

**Comment by ryanwinchester** [comment]
Thanks @geekdevs #41

**Comment by spingary** [comment]
I'd like to add Blog Topics endpoints, and I want to help.  The problem is I am a complete noob with Git. I am currently using Source Tree and trying to learn Git Flow.  

Here's where I am at, and am a bit confused and looking for some pointers.

So I forked the repo, cloned the develop branch and started a new feature. 
My app is written in Laravel, and currently on my app, the repo is added via composer and points to Ryan's main repo.

So here's where I'm stuck:

- Since I cloned the develop branch, the code doesn't really seem up-to-date with master and missing many files. It's not a big deal, but should I have cloned the master and worked off of that instead?
- To use my own version in my app, I read that I am supposed to create by own branch (e.g. dev-custom) and point composer to my repo. Which is fine, but I cannot seem to push my feature updates to that branch. Any idea why? Without being able to do that, my Laravel app will not pull my feature updates and I cannot test them. But if I point my Laravel app to my feature branch, then it won't have the latest endpoints (since it's not based on master).

Any help is most appreciated. 
Gary

**Comment by phena109** [comment]
Hi @spingary ,

It's a coincident that I need the API for Blog Topics too. So I went a little ahead of you submitted (and got accepted) for the the Blog Topics API endpoint. 

Just update the composer version to dev-master and you should get that.

cheers,
phena109

**Comment by ryanwinchester** [comment]
Thanks @phena109
