### ISSUE TITLE
Timeline API

### ISSUE THREAD

**Issue by plaidpowered** [ryanwinchester/hubspot-php#59]
Any plans to implement the Timeline API in the near future?

**Comment by lukevers** [comment]
Hey @plaidpowered (and also @ryanwinchester since this is his repo),

I started working on Timeline API support last night and will probably be putting in a pull request within the next day or so (I just want to make sure to thoroughly test it first).

Thanks @ryanwinchester for the structure of this library as it is. It's been a breeze to add Timeline support.

**Comment by ryanwinchester** [comment]
@lukevers thanks :)

**Comment by lukevers** [comment]
@plaidpowered @ryanwinchester #62

**Comment by ryanwinchester** [comment]
thanks @lukevers
